#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Auteur(s) : Florian Thuin
# This file is part of INGInious
import os
import subprocess
import shlex
from inginious import feedback
from inginious import input


if __name__ == "__main__":
    os.chdir("student")
    input.parse_template("quicksort.py")

    p = subprocess.Popen(shlex.split("python3 quicksort.py"), stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
    make_output = p.communicate()[0].decode('utf-8')


    if p.returncode:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Ca ne peut pas fonctionner: vous vérifiez l'emboîtement des blocs, l'utilisation de TOUS les blocs.\n")
        exit(0)
    if make_output == "True":
        feedback.set_global_result("success")
        feedback.set_global_feedback("Bravo! Vous avez réussi, le patron a décidé de vous engager!")
    else:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Vous vous rendez compte d'une erreur: " + make_output)
